#!/bin/bash

FILENAME=$1
NEWFILE=${FILENAME%%.*}

if [[ $2 == "-pptype" || $3 == "-pptype" ]]
then
	SUFFIX1=".pptype.go"
	cat $1 | ./GoCompiler $NEWFILE$SUFFIX1 -pptype
else
	SUFFIX1=".pretty.go"
	cat $1 | ./GoCompiler $NEWFILE$SUFFIX1
fi
