open CodeGen 
open Symtable
open JasminAst

let create_struct_class go_struct  = 
  let next_var_num = Utils.new_counter 0 in 
  let class_name = !scmap go_struct in 
  { 
    class_name = class_name;
    source = "autogenerated_struct_class";
    top_level_vars = 
      List.map 
        (fun (field_name, gotype) -> 
            let var_number = next_var_num () in 
            { 
              name = field_name;
              var_number = var_number;
              jtype = get_jvm_type gotype;
              init_code = 
                [JInst(Aload_0)] @ 
                (type_init_exps gotype) @ 
                [JInst(PutField(flstring class_name field_name, get_jvm_type gotype))];
            } )
        go_struct;
    methods = [];
  }
